# vi mode
bindkey -v

export PATH=$HOME/bin:$PATH

# Editor
export EDITOR=nvim

# Pager
export PAGER=vimpager

# Language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

### zplug Plugins 
source ~/.zplug/init.zsh

# Can manage local plugins
zplug "~/.zsh", from:local
zplug "chrissicool/zsh-256color"
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "~/.zsh-themes", from:local, as:theme

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
# zplug load --verbose

###  Application specific
## zsh
export HISTFILE=~/.histfile
export HISTSIZE=10000
export SAVEHIST=1000000

## nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

## rclone
export RCLONE_PROGRESS=true

## docker
# launch a temporary shell on a given image
function d() {
  docker run -it --rm $1 /bin/sh
}
# hook into a running container
function nse() {
  docker exec -it $1 sh
}

## direnv
# https://github.com/direnv/direnv
eval "$(direnv hook zsh)"

## rclone
export RCLONE_PROGRESS=true

### Aliases
alias zshconfig="$EDITOR ~/.zshrc && source ~/.zshrc"
alias ll="ls -alh"
alias ubuntu="docker run -it --rm ubuntu"
alias vim="nvim"

### Local
if [ -e $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi
