# vi mode
bindkey -v

export PATH=$HOME/bin:$HOME/.local/bin:$PATH

# Editor
export EDITOR=nvim

# Pager
# export PAGER=vimpager

# Language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Enable coloring of e.g. ls
export CLICOLOR=1

### zplug Plugins
source ~/.zplug/init.zsh

# Can manage local plugins
zplug "~/.zsh", from:local
zplug "chrissicool/zsh-256color"
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "~/.zsh-themes", from:local, as:theme
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
# zplug load --verbose

###  Application specific
## ls
# https://github.com/seebi/dircolors-solarized/issues/10
# export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
export LSCOLORS=exfxfeaeBxxehehbadacea

## zsh-autosuggestions
bindkey '^p' autosuggest-accept

## zsh
export HISTFILE=~/.histfile
export HISTSIZE=10000 export SAVEHIST=1000000
## nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

## rclone
export RCLONE_PROGRESS=true

## docker
# launch a temporary shell on a given image
function d() {
  docker run -it --rm $1 /bin/sh
}
# hook into a running container
function nse() {
  docker exec -it $1 sh
}

## direnv
# https://github.com/direnv/direnv
eval "$(direnv hook zsh)"

## rclone
export RCLONE_PROGRESS=true

##  fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# use fd instead of find to ignore .gitignore, hidden files
# export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}
# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

## pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

### Aliases
alias zshconfig="$EDITOR ~/.zshrc && source ~/.zshrc"
alias ll="ls -alh"
alias ubuntu="docker run -it --rm ubuntu"
alias vim="nvim"

### Local
if [ -e $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi
