# ANTIGEN
# see http://antigen.sharats.me/
source $HOME/.antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
#antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme
#antigen theme robbyrussell
#let's use our a custom theme instead
source $HOME/.zsh-theme
# /ANTIGEN

# PATH
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/bin:$PATH

# EDITOR
export EDITOR=vim

# PAGER
export PAGER=vimpager

# Aliases
alias zshconfig="vim ~/.zshrc && source ~/.zshrc"
alias zshtheme="vim ~/.zsh-theme && source ~/.zshrc"
alias ll="ls -alh"
